/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2023 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 4.1d1 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=a85ac5dd21f4d9c38bf726770e9d9f28 (do not edit this line) */
